### ISSUE TITLE
Restarting an empty resource caused a crash 

### ISSUE THREAD

**Issue by vxlurk** [thorium-cfx/mono_v2_get_started#1]
[CfxCrashDump_2023_05_20_19_16_40.zip](https://github.com/thorium-cfx/mono_v2_get_started/files/11523048/CfxCrashDump_2023_05_20_19_16_40.zip)

Restarting an empty resource casuses a crash

client resource source code:
`
using System;
using System.Diagnostics;
using System.Linq;
using CitizenFX.Core;
using CitizenFX.FiveM;
using CitizenFX.Shared.Native;
using Debug = CitizenFX.Core.Debug;

namespace TestResource.Client;

public class Client : BaseScript
{
  public Client()
  {
  }
}
`

**Comment by thorium-cfx** [comment]
Can't repro this with the given results, can you provide me with an [MRE repro](https://stackoverflow.com/help/minimal-reproducible-example)?

I did however have a look in the logs and I see a lot of resource (re)starts where resources weren't empty, so I'd presume something was up in an earlier version that actually crashed when it was stopped.

**Comment by thorium-cfx** [comment]
Closing this as several resource stop/restart related issues were fixed in the mean time and it's not actionable in the current state.

We can always reopen this issue when you add the requested information.
