### ISSUE TITLE
Ambiguity between string and CString implicit operators

### ISSUE THREAD

**Issue by Sasino97** [thorium-cfx/mono_v2_get_started#13]
### What happened?

I'm converting MenuAPI to the new runtime, and I have found a problem that makes porting a bit more annoying :( 

The following line generates the compilation error below:

```csharp
Debug.WriteLine($"[MenuAPI ({GetCurrentResourceName()})] Error: Could not get currrent menu item, error details: {e.Message}. Current index: {CurrentIndex}. Current menu size: {Size}. Current menu name: {MenuTitle}. List of menu items: {itemsString}.");
```

![image](https://github.com/thorium-cfx/mono_v2_get_started/assets/17410173/66e9b67a-2051-46dd-add0-9b67f24e40e1)

Because it seems there are two implicit operators for OutString: one that converts it to a string, and another that converts it to a CString. I believe it makes more sense for the CString implicit operator not to exist, and to manually do new CString() when needed, rather than manually casting to `(string)` every time we need to convert an OutString to string.

It makes sense that `string` implicitly becomes a `CString` when needed (so we don't have to cast every time we use a native), however it makes less sense to me that `OutString` implicitly converts to `CString`, as it's much rarer that we need call a native and get a string out of it, and then directly use that string as the argument of another native.

### Expected result

Assume `string` automatically (make OutString to CString conversion operator explicit)

### Reproduction steps

```bash
Try to compile this code with mono v2.


Debug.WriteLine($"[MenuAPI ({GetCurrentResourceName()})] Error: Could not get currrent menu item, error details: {e.Message}. Current index: {CurrentIndex}. Current menu size: {Size}. Current menu name: {MenuTitle}. List of menu items: {itemsString}.");
```

### Importancy

Slight inconvenience

### Specific version

6514

**Comment by thorium-cfx** [comment]
Has been fixed as of https://github.com/citizenfx/fivem/commit/f2984de22873d7382d238ec68e32d76a1d72e8e7

**Comment by BlackFlash5** [comment]
> as it's much rarer that we need call a native and get a string out of it, and then directly use that string as the argument of another native.

Might be true that it is 'rare', but it is also not very intuitive to deal with something like this (or at least isn't really 'clean'):
```csharp
string myCoolConfig = Natives.LoadResourceFile(Natives.GetCurrentResourceName(), "config.json");
// Error CS1503 Argument 1: cannot convert from 'CitizenFX.Core.OutString' to 'CitizenFX.Core.CString'
```

In this case adding `.ToCString()` to `Natives.GetCurrentResourceName()` is not an ideal solution.
```csharp
string myCoolConfig = Natives.LoadResourceFile(Natives.GetCurrentResourceName().ToCString(), "config.json");
// Works fine
```

This needs a solution that works with both cases 'as expected' in my opinion.

**Comment by thorium-cfx** [comment]
Interesting, I'll consider bringing back `InString`, that can then allow multiple input types.

**Comment by thorium-cfx** [comment]
Found an easy fix, both use cases will then work
