### ISSUE TITLE
Command-method overloads

### ISSUE THREAD

**Issue by BlackFlash5** [thorium-cfx/mono_v2_get_started#19]
### Goal

For v1 I made a [PR](https://github.com/citizenfx/fivem/pull/194) to implement some overloads for command-methods.
Would it be possible to get them ported to v2?

Especially having the player-object on the server, without 'converting' the handle to a player yourself every time, saves time and improves code readability.

### Importancy

Quality of Life (QoL)

### API and/or potential implementation

```csharp
[Command("trigger")]
private void OnTrigger() { }

[Command("withargs")]
private void OnWithArgs(string[] args) { }

// Server only
[Command("playertrigger")]
private void OnPlayerTrigger(Player player) { }

// Server only
[Command("playertriggerwithargs")]
private void OnPlayerTriggerWithArgs(Player player, string[] args) { }
```

### Extra

Could have thought of this myself in #17, duh...
Used to it for 4 years now tho... :)

**Comment by thorium-cfx** [comment]
Aah, this makes a lot more sense! Wished the command protocol was different, but this is doable without incurring a performance penalty and we can enforce these parameters as well.
