### ISSUE TITLE
Event handlers problems

### ISSUE THREAD

**Issue by vxlurk** [thorium-cfx/mono_v2_get_started#2]
the code: 
https://gist.github.com/vxlurk/d19baf494406dfebae52ade5769f99b2

Creating a local func with `params`  keyword and making it handle an event causes the following error

![image](https://github.com/thorium-cfx/mono_v2_get_started/assets/105105834/61c4ff53-9c8f-465e-a60f-31b498094521)

**Comment by vxlurk** [comment]
Have done some more tests: 
1. Params keyword is ignored not only for local function, but event for instances of a the following delegate
`public delegate void Del(params object[] args);` 
2. Params keyword is ignored for member methods, no matter if I use `Func.Create` or `[EventHandlerAttribute(string evetnName)]`
3. Invoking an event handler `  private void PrivateFuncM(params object[] args)`  causes several errors
  3.1 `Events.TriggerEvent("test", 1, 2, 3, 4)` causes a `System.InvalidCastException`
![image](https://github.com/thorium-cfx/mono_v2_get_started/assets/105105834/471368f8-233a-40f8-902f-f2a4165becd4)
  3.2  `Events.TriggerEvent("test")` causes a `System.NullReferenceException`
![image](https://github.com/thorium-cfx/mono_v2_get_started/assets/105105834/cd69bb16-f0fa-4576-992e-6eed1f35d548)
4. Registering a static method as an event handlers causes a ` System.Reflection.TargetParameterCountException`
![image](https://github.com/thorium-cfx/mono_v2_get_started/assets/105105834/9b9dad1a-6fd3-4e0e-841a-758a4866cd26)

the code I used for the tests
https://gist.github.com/vxlurk/b44503d1952bd4cd29cf6edd046a4698

**Comment by thorium-cfx** [comment]
Thank you for reporting this,

Numbers 1 to 3 are expected results so I expect this to be a feature request on the new `DynFunc` delegates? For now you can actually do it by creating a `DynFunc` with a method with the same signature, e.g.:

```csharp
DynFunc dynFunc = (DynFunc)DirectDynFuncMethod; // you can register this one

private object DirectDynFuncMethod(Remote remote, object[] arguments)
{
	// do things with arguments
}
```

The 4th actually does look like an issue that shouldn't happen, will fix that in one of the upcoming updates.
