### ISSUE TITLE
Need Support for C# Runtimes in Asset Escrow System

### ISSUE THREAD

**Issue by SABogdan** [thorium-cfx/mono_v2_get_started#21]
### Goal

The Asset Escrow system is designed to protect content by ensuring purchase ownership and encrypting resources. However, at present, it only supports Lua 5.4, YFT, and YDR files. Many developers, including myself, use C# runtimes for various functionalities in our projects. The absence of support for C# runtimes in the Asset Escrow system leaves our content vulnerable and limits our ability to fully secure our work.

### Importancy

Nice extra

### API and/or potential implementation

The user interface for the integration of C# runtimes in the Asset Escrow system could be an extension of the existing Asset Escrow system, with added options and configurations specific to C# runtimes

### Extra

This might not be in the objective of this repo.

**Comment by thorium-cfx** [comment]
We are aware there's an interest for Escrow support on C# scripts. Last time I inquired about this I heard there isn't any system that can make this work and requires more R&D to find viable solutions. I haven't yet looked into this personally, but I know it's not a small feat.

That said, this is indeed out of the scope of this project. So these feature requests would need to go to the [forums](https://forum.cfx.re/).
