### ISSUE TITLE
Coroutines scheduled by non-main threads aren't scheduled in the core scheduler

### ISSUE THREAD

**Issue by thorium-cfx** [thorium-cfx/mono_v2_get_started#23]
### What happened?

The core scheduler isn't notified when any action/coroutine is scheduled by any thread apart from the main thread. Supporting this has some design implications, as the current process is solely designed around the main-thread.

### Expected result

Core scheduler will call in when a new action/coroutine has been scheduled outside of the main thread.

### Reproduction steps

```csharp
[Tick]
private async Coroutine Tick()
{
	Debug.WriteLine("Tick runs!");
	await Task.Delay(1000);
}
```

### Importancy

Can't use this feature until fixed

### Specific version

Any since the mono v2 "tick-less" feature

### Extra

Scripts that have other things being scheduled might not experience this issue.

**Comment by ivanzaida** [comment]
May it be the cause of tasks/coroutines not being resolved sometimes?

**Comment by Local9** [comment]
`await Coroutine.Yield();` after a string? bit overkill, and shouldn't be needed.

**Comment by ivanzaida** [comment]
> `await Coroutine.Yield();` after a string? bit overkill, and shouldn't be needed.

that was an attempt to resolve the problem, seems like it has no effect on coroutine being completed at all

**Comment by thorium-cfx** [comment]
> May it be the cause of tasks/coroutines not being resolved sometimes? `Debug.WriteLine("Find after query");` never gets called
> ...

Not unlikely, something needs to be scheduled in the `Coroutine` scheduler while it's being called by FiveM/RedM itself for the core scheduler to call into your script again later.

Your example has a high chance of this Coroutine being scheduled outside of this routine and as a result not notifying the core scheduler, needing something else to schedule it again, e.g.: another tick or scheduling of a coroutine in an event/export call.
