### ISSUE TITLE
Mono rt2 is no longer supported

### ISSUE THREAD

**Issue by DaniGP17** [thorium-cfx/mono_v2_get_started#26]
Hello, hello, I have been experimenting with v2 of c# for fivem, but on September 1 it stopped being supported, is there a possibility of making it continue working?
Thanks

**Comment by thorium-cfx** [comment]
I'll make it available again, yes! Hopefully in the coming days. Sorry for the inconvenience, we've been quite busy lately

**Comment by DaniGP17** [comment]
Thank you so much 💯

**Comment by Alexr03** [comment]
Hey, has this been completed? I see that the prerelease date hasn't been updated in cfx yet.
https://github.com/citizenfx/fivem/blob/9729577be50de537692c3a19e86365a5e0f99a54/code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp#L271

Would like to test again with mono v2 :)

**Comment by Sasino97** [comment]
Also still interested, I have paused my port to July 5, I had completed all the main code, but I have continued my CnR game mode a lot since then

**Comment by thorium-cfx** [comment]
It's active again on latest! Sorry that it took so long, we had some technical difficulties.

**Comment by DaniGP17** [comment]
> It's active again on latest! Sorry that it took so long, we had some technical difficulties.

No problem, thank you so much for your effort ❤️
