### ISSUE TITLE
Remote event argument type affects the call of the handler

### ISSUE THREAD

**Issue by Marky-S** [thorium-cfx/mono_v2_get_started#30]
### What happened?

I created remote event from client to server with arguments like `[uint modelHash, string modelType]` and received this error:
```
SCRIPT ERROR: Could not invoke event handler Action
[script:core]   expected: (CitizenFX.Core.Remote, Object[])
[script:core]   received: (UInt32               , String  )
```

### Expected result

Correct event handling

### Reproduction steps

1. Trigger server event from client with first `uint` arg
```csharp
// ...client... //
Events.TriggerServerEvent("myEvent", modelHash, modelType); // args [uint, string]
```
2. Handle this event on server with `DynFunc` delegate
```csharp
// ...server... //
EventHandlers["myEvent"].Add(wrapperInstance.Action, Binding.All);

// ...wrapper instance class... //
public object Action(Remote remote, params object[] args)
```

### Importancy

Slight inconvenience

### Extra

After some research I was able to solve this problem simply by changing the type of the first argument from `uint` to  `int` and code above works fine.
```csharp
// ...client... //
Events.TriggerServerEvent("myEvent", (int)modelHash, modelType);
```

**Comment by thorium-cfx** [comment]
I'm unable to reproduce it with the given repro steps, the `int` version also doesn't make sense in this context. Can you supply more of the error and code on this? Especially what you run in the `Action` method.

Do note that the error helper (expected & received info) only applies for wrappers, i.e.: any made through `Func.Create`, therefore its information is useless on non-wrappers, like the ones you use now.

**Comment by Marky-S** [comment]
Yeah, second time this is was error in my wrapper-method.

I always get confused with the error context because of this part of the exception:
```bash
[script:core] SCRIPT ERROR: Could not invoke event handler Action
[script:core]   expected: (CitizenFX.Core.Remote, Object[])
[script:core]   received: (UInt32               , String  )
[script:core]   * Any type in red is not convertible, castable, or simply missing and requires attention.
```
`expected` and `received` fields both contained red arguments.

I'll be more attentive in the future
