### ISSUE TITLE
Improvement compared to external libraries?

### ISSUE THREAD

**Issue by DaniGP17** [thorium-cfx/mono_v2_get_started#33]
### Goal

First of all, I want to apologize because I know this is not the place to ask this question.

My question is whether this V2 has a longer execution time than the previous one, I want to make a script that will be based mainly on a library and although V2 can be used, I would like to know if the execution speed of the library is independent of the environment of execution.
Because I'm a little worried about the mono flag potentially expiring and causing people who use my script to stop working.

Thanks in advance.

### Importancy

Prerequisite for my project

Edit: I have been testing and the performance of the mysqlconnector library is very different in the current version of C# than in V2.

Here I will show the execution averages of queries with the same code but using different versions.
V1:
```
Average results from 1000 iterations (ms)
0.4295ms
```

V2:
```
Average results from 1000 iterations (ms)
0.0911 ms
```

Therefore, it would be better for me to use V2 because everything works but the problem is the mono flag.

**Comment by Sasino97** [comment]
Guys mono v2 was very likely discontinued

**Comment by DaniGP17** [comment]
I hope that when they have time they continue it because it is just what the C# version of Fivem was missing, I don't know what it needs to do either, right now I think that most of the possibilities that FiveM offers can be used

**Comment by thorium-cfx** [comment]
Hello Dani, mono rt2 (v2) is still on our roadmap. We currently have other projects that take precedence and will add quite some changes to this environment as well, once those are finished we can finally continue this environment and plan on releasing it.

Regarding your initial question: performance of external libraries shouldn't change, outside of `Task` related scheduling, which is no longer manually handled in v2, maybe that's influencing your test code? Apart from that you could expect performance increases in anything in the `CitizenFX.*` namespace, i.e.: our assemblies.

Hope this answers your question.

**Comment by DaniGP17** [comment]
> Regarding your initial question: performance of external libraries shouldn't change, outside of Task related scheduling, which is no longer manually handled in v2, maybe that's influencing your test code? Apart from that you could expect performance increases in anything in the CitizenFX.* namespace, i.e.: our assemblies.

Thanks for answering, what I have been doing has been creating an export to perform a query using the same code in V2 and V1 and from lua I have executed the benchmark, that is why I ask if V2 can have a higher execution speed of the libraries, you have said that the CFX functions will work faster, I don't know if this has to do with the explanation of my doubt.

**Comment by DaniGP17** [comment]
The last question, then the V2 export system is much more optimized from what I have been able to understand, the same thing happens to the execution of events or could I make my own export system to be able to optimize it for the v1 of mono?
