### ISSUE TITLE
With latest client build (7788) C# BaseScript and Coroutine .Wait stop runtime (reproduction repo added)

### ISSUE THREAD

**Issue by Gyzzmo** [thorium-cfx/mono_v2_get_started#36]
### What happened?

Hi !

Since client version 7788 (so canary too), any C# Coroutine.Wait or BaseScript.Wait/WaitFor... stop script execution. 
No error, just wait infinitely.

That said WaitUntil(TimePoint) only works.

This issue can be see with FxDK and with a client/server.

### Expected result

Just wait correctly

### Reproduction steps

```bash
Show this repo: https://github.com/Gyzzmo/mono_v2_bug/tree/master
```

### Importancy

Fatal (we can't use the runtime without)

### Specific version

FiveM windows since build 7788

**Comment by Gyzzmo** [comment]
I dont have try older versions, I've just discovered that recently. I try previous versions to find precisely the version of FXServer where this bug started.

**Comment by Gyzzmo** [comment]
Reproduction repo: https://github.com/Gyzzmo/mono_v2_bug/tree/master

**Comment by thorium-cfx** [comment]
Thank you for this report, confirmed this happens at any second `Wait` call. Looking into how to fix this
