### ISSUE TITLE
Intervals

### ISSUE THREAD

**Issue by Marky-S** [thorium-cfx/mono_v2_get_started#8]
### Goal

Run intervals such as JavaScript `setInterval()` directly from scheduler.

### Importancy

Quality of Life (QoL)

### API and/or potential implementation

```c#
int intervalCookie = Scheduler.SetInterval(Action coroutine, ulong interval); // create
...
void Scheduler.ClearInterval(int intervalCookie); // stop and destroy
```

**Comment by thorium-cfx** [comment]
Interesting addition, can go together with another request to start a delayed action.

I do want to find different words for **interval** as it's a misnomer for such operations and technically incorrect. **Interval** *(singular)* meaning "an intervening time or space" among other similar, i.e.: not repeating, only with time in between. **Set** also needs consideration, your comments "create" and "stop and destroy" are already more descriptive.

**Comment by Marky-S** [comment]
I completely agree with you, it looks much better this way

**Comment by thorium-cfx** [comment]
`Cancel` sounds good, will probably get to this in the next set of feature changes

**Comment by thorium-cfx** [comment]
I ended up with the following:

```csharp
// single delayed execution:
await Coroutine.Schedule(myAction, delay);

Canceler canceler = new Canceler(); // { ThrowOnCancelation = true };
await Coroutine.Schedule(myAction, delay, canceler);


// repeating delayed execution:
await Coroutine.Schedule(myAction, delay, iterations); // repeats x amount of iterations
await Coroutine.Schedule(myAction, delay, Repeat.Infinite); // repeats infinitely

Canceler canceler = new Canceler(); // { ThrowOnCancelation = true };
await Coroutine.Schedule(myAction, delay, iterations, canceler); //  repeats x amount of iterations
await Coroutine.Schedule(myAction, delay, Repeat.Infinite, canceler); // repeats infinitely

* myAction: Action or Func<Coroutine>
* delay: ulong
* iterations: ulong, Repeat.Infinite or ulong.MaxValue for infinite runs
* canceler: CancelerToken
* `await Coroutine.Schedule(...)` for async await
* `_ = Coroutine.Schedule(...)` for async non-await, equivalent to JS' `setTimeout` and `setInterval`
```
