### ISSUE TITLE
StateBag.Global not accessible

### ISSUE THREAD

**Issue by BlackFlash5** [thorium-cfx/mono_v2_get_started#9]
### Goal

The static `Global`-property in `StateBag`-class has no access modifier which makes it private - this leads to an inaccessible global state bag.
I'm not sure if there is a specific reason for this, but the goal would be to have an accessible global state bag.

### Importancy

Overal quality to the runtime

### API and/or potential implementation

Add `public` access modifier to property [static StateBag Global => new StateBag("global");](https://github.com/citizenfx/fivem/blob/1e325970371bd5872a9f7bf627f45455b4e367cc/code/client/clrcore-v2/StateBag.cs#L11)

Usage example:
```c#
StateBag.Global.Set("test123", ":)", true);
string test = StateBag.Global["test123"];
```

**Comment by thorium-cfx** [comment]
That's been an oversight, will be fixed in the next update

**Comment by thorium-cfx** [comment]
Fixed in build 6500. Thank you for reporting this!
